USE [master]
GO

/****** Object:  Database [RRD]    Script Date: 4/30/2018 8:07:34 PM ******/
DROP DATABASE [RRD]
GO

/****** Object:  Database [RRD]    Script Date: 4/30/2018 8:07:34 PM ******/
CREATE DATABASE [RRD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RRD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\RRD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RRD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\RRD_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RRD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RRD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RRD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RRD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RRD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RRD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RRD] SET ARITHABORT OFF 
GO

ALTER DATABASE [RRD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RRD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RRD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RRD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RRD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RRD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RRD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RRD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RRD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RRD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RRD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RRD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RRD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RRD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RRD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RRD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RRD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RRD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RRD] SET  MULTI_USER 
GO

ALTER DATABASE [RRD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RRD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RRD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RRD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RRD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RRD] SET  READ_WRITE 
GO

